name: SLATE Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Pull down automation script
        run: curl -fsSL https://raw.githubusercontent.com/slateci/gitops-automation-script/main/PushUpdates.py -o PushUpdates.py

      - name: Install Python dependencies
        run: pip install -U requests

      - name: Deploy to SLATE
        id: deploy
        run: |
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.event.after }}"

          # https://stackoverflow.com/questions/40883798/how-to-get-git-diff-of-the-first-commit
          if [[ $BEFORE = "0000000000000000000000000000000000000000" ]]; then
            BEFORE="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
          fi

          if [[ $AFTER = "0000000000000000000000000000000000000000" ]]; then
            AFTER="4b825dc642cb6eb9a060e54bf8d69288fbee4904"
          fi

          git diff --name-status --pretty="format:" "$BEFORE" "$AFTER" > .changed
          echo "::set-output name=DIFF_OUTPUT::$(git diff "$BEFORE" "$AFTER")"
          python3 PushUpdates.py ".changed" "${{ secrets.SLATE_API_TOKEN }}"
          rm .changed

      # Uncomment this out if you'd like Mailgun notifications.
      # - name: Email Changes
      #   uses: vineetchoudhary/mailgun-action@master
      #   with:
      #     api-key: ${{ secrets.MAILGUN_API_KEY }}
      #     domain: ${{ secrets.MAILGUN_DOMAIN }}
      #     to: ${{ secrets.MAILGUN_SEND_TO }}
      #     cc: ${{ secrets.MAILGUN_CC_TO }}
      #     from: ${{ secrets.MAILGUN_FROM }}
      #     subject: "SLATE GitOps Change Summary"
      #     body: "Here's the diff of changes made:\n\n${{ steps.deploy.outputs.DIFF_OUTPUT }}"

      - name: Commit SLATE Instance ID
        if: ${{ steps.deploy.outputs.push == 'true' }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "append new SLATE instance ID" --allow-empty
          git push
