name: SLATE Deployment

on:
  push:
    branches:
      - master # (or main, etc.)

jobs:
  deploy:
    name: Deploy
    uses: slateci/github-actions/.github/workflows/slate-deployment.yml@master
    with:
      mailgun_send_to: "sample@no-reply.com"
    secrets:
      mailgun_api_key: "${{ secrets.MAILGUN_API_KEY }}"
      slate_api_token: "${{ secrets.SLATE_API_TOKEN }}"
